### ISSUE TITLE
Should be able to Name and Edit Custom Commands

### ISSUE THREAD

**Issue by skewty** [elementary/session-settings#10]
Currently you can only add custom commands.  I believe the Name= and Exec= lines should be editable by the user through the GUI.  This shouldn't be too difficult.

Full CRUD abilities are the user expectation.

**Comment by arshubham** [comment]
Icon name should also be editable, or better use the same icon chooser from Appeditor, with ability to give custom path.

![image](https://user-images.githubusercontent.com/14235191/45695526-3d63ee00-bb7f-11e8-9f5b-110dee2411ec.png)

**Comment by cassidyjames** [comment]
This issue was moved to elementary/switchboard-plug-applications#29
