### ISSUE TITLE
gnome session: remove ubuntu fallback

### ISSUE THREAD

**Issue by decathorpe** [elementary/session-settings#11]
On a default elementaryOS install, the ubuntu session isn't even present.

Moreover, since unity is gone, isn't the default session on ubuntu GNOME now, anyway? (Or is the tweaked ubuntu-ified GNOME session now called "ubuntu"?)

**Comment by codygarver** [comment]
Ubuntu's .session still identifies as ubuntu so I never changed this.

**Comment by worldofpeace** [comment]
We can use `fallback-session` as a meson option to configure this now.

@codygarver Not sure why this didn't get closed, can you?
