### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by btd1337** [elementary/session-settings#14]
Is it possible to make a new release with the latest updates?

**Comment by LinArcX** [comment]
Yes. I'm packaging pantheon for void linux and need new release. Since latest release doesn't have meson.build!

**Comment by btd1337** [comment]
Did this task have any updates?

**Comment by worldofpeace** [comment]
Likely in 6.0 because there's so many changes and one's that aren't compatible with Juno

**Comment by quequotion** [comment]
Does the removal of this from the 6.0 project mean it won't happen?

**Comment by NotAlexNoyle** [comment]
> Does the removal of this from the 6.0 project mean it won't happen?

Curious about this too. Is a new distro-agnostic release of pantheon in the cards any time soon?

**Comment by davidmhewitt** [comment]
It's done, there was a release 3 days ago
