### ISSUE TITLE
Figure out required GSD plugins for focal

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/session-settings#18]
Some of the GSD plugins we have listed as required components of the session no longer exist in focal, so we will need to remove some and figure out if any new ones added replace those functionalities or provide new features we want/need.

**Comment by danrabbit** [comment]
in f9576162da46efd35ae481d362ed4872cbb94469 we dropped org.gnome.SettingsDaemon.Clipboard and org.gnome.SettingsDaemon.Mouse

It looks like the Mouse plugin was removed/combined with the XSettings plugin: https://github.com/GNOME/gnome-settings-daemon/commit/c58539784f23622bcc746e95d7f4755f53981f3e

Reveal cursor used to be part of this but it was moved to Mutter/GNOME Shell: https://github.com/GNOME/gnome-settings-daemon/commit/6dff93a0dfa80db3f481eed5d6ed689bf469aa1b

https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/413

It looks like dwell click and long press click settings were also moved to Mutter/GNOME Shell: https://github.com/GNOME/gnome-settings-daemon/commit/9d5e1d9c0f7b0b702372c47fb81fad7cf3a4085f

https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/474

And it looks like the clipboard stuff was merged into Mutter: https://github.com/GNOME/gnome-settings-daemon/commit/f0b38977e97687d668005c6ea85fa9121739a369

**Comment by danrabbit** [comment]
I've filed issues about this in relevant projects, so I think we can close this:

https://github.com/elementary/gala/issues/715

https://github.com/elementary/wingpanel-indicator-a11y/issues/30
