### ISSUE TITLE
How start pantheon-shell without using a display manager?

### ISSUE THREAD

**Issue by LinArcX** [elementary/session-settings#24]
This is not a but-report. Just a question.
I'm using pantheon desktop environment on void linux. Currently i should install lightdm,  gnome-shell to actually start pantheon shell. Arch wiki said:

>     Alternatively, you can use ~/.xinitrc
>     to launch the Pantheon shell, by adding exec cerbere
>     to the end of the file.

But unfortunately it's not working on void linux.

In general, is it possible to start pantheon-shell with startx command(without depending on gnome-shell or lightdm/gdm?)

**Comment by davidmhewitt** [comment]
Cerbere has been discontinued, I wouldn't recommend using it.

You also shouldn't need gnome-shell. You will need gnome-settings-daemon and probably gnome-session however.

We launch Pantheon with `gnome-session --session=pantheon` with `pantheon.session` correctly installed in gnome-session 's session folder, which is at `/usr/share/gnome-session/sessions` on Ubuntu based distros.

**Comment by LinArcX** [comment]
> Cerbere has been discontinued, I wouldn't recommend using it.
So, what is the alternative?

> You will need gnome-settings-daemon and probably gnome-session however.
I have both of them on my machine.

> We launch Pantheon with gnome-session --session=pantheon with pantheon.session correctly installed in gnome-session 's session folder, which is at /usr/share/gnome-session/sessions

Yeah, I have this file too. Actually everything is fine with lightdm.

As i've said, I want to start pantheon-shell with startx(without using any display manager).

**Comment by davidmhewitt** [comment]
`gnome-session` is the alternative. It's a very small process that manages the session and starts/restarts components, just like cerbere did.

What happens if you run `gnome-session --session=pantheon` in your startx script instead of `cerbere` ?

**Comment by LinArcX** [comment]
I see something like [this](https://4.bp.blogspot.com/-F45EPsznQNs/VHiTNETaD0I/AAAAAAAACII/euKz6c5OPrA/s1600/vnc1.png
)

And this is the [stderr](https://gist.github.com/LinArcX/94d28b9d4e46e23cb407a67af1e1c5c8).

**Comment by davidmhewitt** [comment]
This big block of warnings is the first thing you need to fix:
```
gnome-session-binary[16444]: WARNING: Could not get session id for session. Check that logind is properly installed and pam_systemd is getting used at login.
gnome-session-binary[16444]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Clipboard'
gnome-session-binary[16444]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Mouse'
gnome-session-binary[16444]: WARNING: Could not parse desktop file libcanberra-login-sound.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.XSettings-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Power-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.A11ySettings-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Housekeeping-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Rfkill-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Mouse-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Datetime-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.PrintNotifications-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file xscreensaver.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Sound-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Smartcard-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Clipboard-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Color-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Wacom-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Keyboard-pantheon.desktop or it references a not found TryExec binary
gnome-session-binary[16444]: WARNING: Could not parse desktop file org.gnome.SettingsDaemon.Sharing-pantheon.desktop or it references a not found TryExec binary
```

It seems you have a problem with logind as described in the first warning.

I also imagine you're using a different version of `gnome-settings-daemon` compared to the version that our session files were written for. Different versions of g-s-d put files in different places and add/remove components. So it seems for the version you have in void, you'll need to update the `RequiredComponents` line in `pantheon.session` and remove 'org.gnome.SettingsDaemon.Clipboard' and 'org.gnome.SettingsDaemon.Mouse' as the errors say they don't exist. 

Then you'll need to update the `Exec` and `TryExec` lines in all of the org.gnome.SettingsDaemon.*-pantheon.desktop files to have the correct path for when those g-s-d binaries are installed in Void.

Once you've fixed all those warnings, if it still doesn't work, let us know some more details.

**Comment by LinArcX** [comment]
Yes!
It's working now. I've just installed `pipewire`.
A question about license of this repo. What is it? GPL-3 or GPL-2?
(Since i should fork it and change all `org.gnome.SettingsDaemon.*-pantheon.desktop` to compatible with void echo system)

**Comment by davidmhewitt** [comment]
I'm not sure about the license, can you open another issue in this repo about the missing license file and hopefully someone else will fix that or respond...

I'll close this issue now since you seem to be making progress. Good luck!

**Comment by LinArcX** [comment]
> Cerbere has been discontinued, I wouldn't recommend using it.

>You also shouldn't need gnome-shell. You will need gnome-settings-daemon and probably gnome-session however.

What about [dpms-helper](https://github.com/elementary/dpms-helper)? Is it necessary?
