### ISSUE TITLE
gnome-settings-daemon: /usr/libexec or /usr/lib

### ISSUE THREAD

**Issue by quequotion** [elementary/session-settings#30]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
If elementary OS follows the the [FHS 2.3 specification](https://www.pathname.com/fhs/), there is no `/usr/libexec`, so gsd's plugins should be installed to `/usr/lib` and the autostarts in this package should have `Exec=` lines pointing to them there, [as I previously suggested](https://github.com/elementary/session-settings/pull/21). 

## Additional context
I don't see a gsd-focal branch in os-patches yet. Is elementary OS planning to use "vanilla" gsd* in the next release? If the gsd package supplied by Ubuntu is installing them to libexec, that's probably breaking their own policy (in theory, Ubuntu follows the FHS specification) and should be reported. 

*I don't actually mean the real, vanilla gsd, but the package inherited form Ubuntu which probably has Canonical and Debian patches.

**Comment by quequotion** [comment]
SolarAquarion's PR #28  would very likely resolve this by allowing the paths used in the startups and session file to be defined by the distribution for which they are compiled.

**Comment by tintou** [comment]
FYI: `/usr/libexec` is included in [FHS 3.0 specification](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html)

**Comment by quequotion** [comment]
Oh gosh, don't tell the Archlinux people.

Anyway, I think this issue is bypassed by https://github.com/elementary/session-settings/commit/130c9ae221913032ed18bcf6d21e3dcdba3c4209
