### ISSUE TITLE
Grant worldofpeace write access to session-settings

### ISSUE THREAD

**Issue by worldofpeace** [elementary/session-settings#32]
# Description
Hi, I hope this is an appropriate way to ask for this.
I wish to maintain this project, as I've made several contributions to it that has rewritten its build system.
My interest and experience is looking out for downstreams that will have interest in this project, and working with them so it can remain compatible with hopefully as many as possible. Being a nixos maintainer, no environment is arcane to me anymore :grin: 

Another important thing is the Nix code in CI https://github.com/elementary/session-settings/blob/master/default.nix and the workflow https://github.com/elementary/session-settings/blob/master/.github/workflows/main.yml#L25. Eventually I'd like to remove this from the repo so we could use the expression in nixpkgs, perhaps nix flakes could help with that https://github.com/NixOS/rfcs/pull/49. As I am a member from NixOS, my interest in this project stems with distributing it there. (and having integrated elementary projects) I have a good knowledge of the workings of the elementary projects because of this.

Thanks - worldofpeace

cc @cassidyjames  @danrabbit

**Comment by worldofpeace** [comment]
My contribution pulse for reference is `3 commits  675 ++  692 --`

**Comment by danrabbit** [comment]
done :+1:

**Comment by worldofpeace** [comment]
Thanks @danrabbit :heart:
