### ISSUE TITLE
G-S-D Plugins in RequiredComponents; really a good idea?

### ISSUE THREAD

**Issue by quequotion** [elementary/session-settings#4]
If anything listed in RequiredComponents fail to start, or crash after starting, gnome-session will crash:
https://github.com/elementary/session-settings/blob/8bd5b3c933d5dc792ef7fa544817de46d06e8a65/gnome-session/pantheon.session#L3

When gnome-session crashes, either the user will find themselves back in their desktop manager or facing a white screen-of-death. That screen locks out the desktop with the rather uninformitive message "Oh no! Something has gone wrong. A problem has occured and the system can't recover. Please log out and try again." and a single "Log Out" button (I have a number of gripes about this screen that are best to discuss with GNOME upstream). Lately I haven't encountered it, but I have been dumped back into LightDM, often leaving a zombified failed session that must be killed with `loginctl` in a TTY before subsequent sessions can be initiated safely (a problem for either LightDM, systemd, or GNOME upstream). I think it best to avoid either scenario if at all possible, given the unlikelyhood that either can be improved (GNOME likes their WSOD; no one wants to take responsibility for the zombified sessions problem).

In any case, these G-S-D plugins are already autostarted by the xdg autostarts provided in this package; it would be redundant to be using the .session file to autostart them. Their listing as RequiredComponents primarily serves to ensure that gnome-session will crash if any of them fail, and secondarily prevents users from disabling any plugins they deem unneccessary. Are they critical enough to warrant that behavior?

**Comment by codygarver** [comment]
This was necessary before GSD 3.27 and has been removed now that 3.2.7 has landed in Bionic.

**Comment by quequotion** [comment]
Good news! Thanks for the update!

**Comment by quequotion** [comment]
Why was this reverted?
https://github.com/elementary/session-settings/commit/c1310e9bc1b855df578e90696ad437c3f49b4934

**Comment by quequotion** [comment]
Probably also the cause of this:
https://www.reddit.com/r/elementaryos/comments/b9flll/cant_login_entering_password_takes_me_back_to/
