### ISSUE TITLE
Power settings

### ISSUE THREAD

**Issue by bksubhuti** [elementary/session-settings#8]
I would like to see ALL the power settings separate for plugged in and battery.
Currently, only only the bottom settings "Dim display when inactive" is separate for batter and plugged in.

A good and common example would be screen brightness.
I would like screen brightness to be maxed out (or any separate setting) when plugged in.

Other things would also be interesting to have when plugged in.

**Comment by davidmhewitt** [comment]
This should be moved to: https://github.com/elementary/switchboard-plug-power/issues

**Comment by danrabbit** [comment]
Closing because this is out of scope for session settings
